name: cern_flavour_school
channels:
  - conda-forge
dependencies:
  - python=3.10  
  - root         
  - numpy
  - pandas
  - scipy
  - matplotlib
  - mplhep
  - pip
  - pip:
    - iminuit>=2.0
    - zfit
